### ISSUE TITLE
New item border color (green) overlaps with old item border color (red) on first old item

### ISSUE THREAD

**Issue by oxjoe** [oxjoe/GimmeTheFreeStuff#2]
Border color overlaps on the first false item, I think I would have to use an iterator in the row factory if that works but I'm not sure.
![capture](https://user-images.githubusercontent.com/3356838/29107862-452831c4-7caa-11e7-9f19-ed83a7b7d1b2.PNG)

#### MainController.java
```java
    // Sets the colors for the row, using the corresponding ID from main.css
    tableView.setRowFactory(tv -> new TableRow<Item>() {
      @Override
      public void updateItem(Item item, boolean empty) {
        super.updateItem(item, empty);
        if (item == null) {
          this.setId("rowOldItem");
        } else if (item.isStatus()) {
          this.setId("rowNewItem"); // sets green
        } else if (!item.isStatus()) {
          this.setId("rowOldItem"); // sets red
        }
      }
    });
```
#### main.css
```css
#rowNewItem{
  /*-fx-background-color: limegreen;*/
  -fx-border-color: limegreen;
}

#rowOldItem {
  /*-fx-background-color: orangered;*/
  -fx-border-color: orangered;
}
```
